apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
commonLabels:
  app: bentobox-engine
  part-of: bentobox
namePrefix: bentobox-
images:
- name: bentobox-engine
  newName: ghcr.io/bentobox-dev/bentobox-engine
  newTag: 89e17a3
